<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>ETrobocon2017: str/googletest/googletest/test/gtest_catch_exceptions_test.py ソースファイル</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">ETrobocon2017
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- 構築: Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'検索');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','検索');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d22/gtest__catch__exceptions__test_8py_source.html','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">gtest_catch_exceptions_test.py</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../df/d22/gtest__catch__exceptions__test_8py.html">[詳解]</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html">    1</a></span>&#160;<span class="comment">#!/usr/bin/env python</span></div><div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="comment">#</span></div><div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="comment"># Copyright 2010 Google Inc.  All Rights Reserved.</span></div><div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="comment">#</span></div><div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="comment"># Redistribution and use in source and binary forms, with or without</span></div><div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="comment"># modification, are permitted provided that the following conditions are</span></div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="comment"># met:</span></div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="comment">#</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="comment">#     * Redistributions of source code must retain the above copyright</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="comment"># notice, this list of conditions and the following disclaimer.</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="comment">#     * Redistributions in binary form must reproduce the above</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="comment"># copyright notice, this list of conditions and the following disclaimer</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="comment"># in the documentation and/or other materials provided with the</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="comment"># distribution.</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="comment">#     * Neither the name of Google Inc. nor the names of its</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="comment"># contributors may be used to endorse or promote products derived from</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="comment"># this software without specific prior written permission.</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="comment">#</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="comment"># THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="comment"># &quot;AS IS&quot; AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT</span></div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;<span class="comment"># LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR</span></div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;<span class="comment"># A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT</span></div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;<span class="comment"># OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,</span></div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;<span class="comment"># SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT</span></div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;<span class="comment"># LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,</span></div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;<span class="comment"># DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY</span></div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;<span class="comment"># THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT</span></div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;<span class="comment"># (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE</span></div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;<span class="comment"># OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</span></div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;<span class="stringliteral">&quot;&quot;&quot;Tests Google Test&#39;s exception catching behavior.</span></div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;<span class="stringliteral"></span></div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;<span class="stringliteral">This script invokes gtest_catch_exceptions_test_ and</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;<span class="stringliteral">gtest_catch_exceptions_ex_test_ (programs written with</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;<span class="stringliteral">Google Test) and verifies their output.</span></div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;<span class="stringliteral">&quot;&quot;&quot;</span></div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;</div><div class="line"><a name="l00038"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a26e1831a55209b037dc7d8d3ca1e4f32">   38</a></span>&#160;__author__ = <span class="stringliteral">&#39;vladl@google.com (Vlad Losev)&#39;</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;<span class="keyword">import</span> os</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="keyword">import</span> gtest_test_utils</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="comment"># Constants.</span></div><div class="line"><a name="l00045"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a2d40f89077ec9fdb51008c263148315f">   45</a></span>&#160;FLAG_PREFIX = <span class="stringliteral">&#39;--gtest_&#39;</span></div><div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a68601cbcd48065a2f656eb8552784f0c">   46</a></span>&#160;LIST_TESTS_FLAG = FLAG_PREFIX + <span class="stringliteral">&#39;list_tests&#39;</span></div><div class="line"><a name="l00047"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#af3e2719448df6b24d78c870e5b586e8b">   47</a></span>&#160;NO_CATCH_EXCEPTIONS_FLAG = FLAG_PREFIX + <span class="stringliteral">&#39;catch_exceptions=0&#39;</span></div><div class="line"><a name="l00048"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a1a53cfa4c10fe3bdbc85a14fd9692751">   48</a></span>&#160;FILTER_FLAG = FLAG_PREFIX + <span class="stringliteral">&#39;filter&#39;</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"># Path to the gtest_catch_exceptions_ex_test_ binary, compiled with</span></div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;<span class="comment"># exceptions enabled.</span></div><div class="line"><a name="l00052"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a2154a0f0c4c506089d686c1365d288be">   52</a></span>&#160;EX_EXE_PATH = <a class="code" href="../../d2/d4a/namespacegtest__test__utils.html#a89ed3717984a80ffbb7a9c92f71b86a2">gtest_test_utils.GetTestExecutablePath</a>(</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;    <span class="stringliteral">&#39;gtest_catch_exceptions_ex_test_&#39;</span>)</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;<span class="comment"># Path to the gtest_catch_exceptions_test_ binary, compiled with</span></div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;<span class="comment"># exceptions disabled.</span></div><div class="line"><a name="l00057"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a164e7815d55b13a811ce60e2e6f9448d">   57</a></span>&#160;EXE_PATH = <a class="code" href="../../d2/d4a/namespacegtest__test__utils.html#a89ed3717984a80ffbb7a9c92f71b86a2">gtest_test_utils.GetTestExecutablePath</a>(</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;    <span class="stringliteral">&#39;gtest_catch_exceptions_no_ex_test_&#39;</span>)</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;</div><div class="line"><a name="l00060"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#ae51b794c28e667016c180f1b3fc85292">   60</a></span>&#160;environ = gtest_test_utils.environ</div><div class="line"><a name="l00061"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a60be14c2b88aafb689ba4d3d2578449e">   61</a></span>&#160;SetEnvVar = gtest_test_utils.SetEnvVar</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="comment"># Tests in this file run a Google-Test-based test program and expect it</span></div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;<span class="comment"># to terminate prematurely.  Therefore they are incompatible with</span></div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;<span class="comment"># the premature-exit-file protocol by design.  Unset the</span></div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;<span class="comment"># premature-exit filepath to prevent Google Test from creating</span></div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;<span class="comment"># the file.</span></div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;<a class="code" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a60be14c2b88aafb689ba4d3d2578449e">SetEnvVar</a>(gtest_test_utils.PREMATURE_EXIT_FILE_ENV_VAR, <span class="keywordtype">None</span>)</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;</div><div class="line"><a name="l00070"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#ac0cf90f54624335d1765e85cf6a74e21">   70</a></span>&#160;TEST_LIST = <a class="code" href="../../d8/dd3/classgtest__test__utils_1_1_subprocess.html">gtest_test_utils.Subprocess</a>(</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;    [EXE_PATH, LIST_TESTS_FLAG], env=environ).output</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;</div><div class="line"><a name="l00073"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a237f68d721da53e9fd4f83b07a1887e3">   73</a></span>&#160;SUPPORTS_SEH_EXCEPTIONS = <span class="stringliteral">&#39;ThrowsSehException&#39;</span> <span class="keywordflow">in</span> TEST_LIST</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;<span class="keywordflow">if</span> SUPPORTS_SEH_EXCEPTIONS:</div><div class="line"><a name="l00076"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a27d8da05609f357df39614cd41516993">   76</a></span>&#160;  BINARY_OUTPUT = <a class="code" href="../../d8/dd3/classgtest__test__utils_1_1_subprocess.html">gtest_test_utils.Subprocess</a>([EXE_PATH], env=environ).output</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;</div><div class="line"><a name="l00078"></a><span class="lineno"><a class="line" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a012f2b0e05fd56aa6817595da940c891">   78</a></span>&#160;EX_BINARY_OUTPUT = <a class="code" href="../../d8/dd3/classgtest__test__utils_1_1_subprocess.html">gtest_test_utils.Subprocess</a>(</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;    [EX_EXE_PATH], env=environ).output</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;<span class="comment"># The tests.</span></div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;<span class="keywordflow">if</span> SUPPORTS_SEH_EXCEPTIONS:</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;  <span class="comment"># pylint:disable-msg=C6302</span></div><div class="line"><a name="l00085"></a><span class="lineno"><a class="line" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html">   85</a></span>&#160;  <span class="keyword">class </span><a class="code" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html">CatchSehExceptionsTest</a>(<a class="code" href="../../d2/d4a/namespacegtest__test__utils.html#acb97a85206c09d233db6c7f2362e5428">gtest_test_utils.TestCase</a>):</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Tests exception-catching behavior.&quot;&quot;&quot;</span></div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;</div><div class="line"><a name="l00089"></a><span class="lineno"><a class="line" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a737bbcc64405854aa8e0aea87ca5850b">   89</a></span>&#160;    <span class="keyword">def </span><a class="code" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a737bbcc64405854aa8e0aea87ca5850b">TestSehExceptions</a>(self, test_output):</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;      self.assert_(<span class="stringliteral">&#39;SEH exception with code 0x2a thrown &#39;</span></div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;                   <span class="stringliteral">&#39;in the test fixture\&#39;s constructor&#39;</span></div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                   <span class="keywordflow">in</span> test_output)</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;      self.assert_(<span class="stringliteral">&#39;SEH exception with code 0x2a thrown &#39;</span></div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;                   <span class="stringliteral">&#39;in the test fixture\&#39;s destructor&#39;</span></div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                   <span class="keywordflow">in</span> test_output)</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;      self.assert_(<span class="stringliteral">&#39;SEH exception with code 0x2a thrown in SetUpTestCase()&#39;</span></div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                   <span class="keywordflow">in</span> test_output)</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;      self.assert_(<span class="stringliteral">&#39;SEH exception with code 0x2a thrown in TearDownTestCase()&#39;</span></div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;                   <span class="keywordflow">in</span> test_output)</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;      self.assert_(<span class="stringliteral">&#39;SEH exception with code 0x2a thrown in SetUp()&#39;</span></div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                   <span class="keywordflow">in</span> test_output)</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;      self.assert_(<span class="stringliteral">&#39;SEH exception with code 0x2a thrown in TearDown()&#39;</span></div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;                   <span class="keywordflow">in</span> test_output)</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;      self.assert_(<span class="stringliteral">&#39;SEH exception with code 0x2a thrown in the test body&#39;</span></div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;                   <span class="keywordflow">in</span> test_output)</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;</div><div class="line"><a name="l00107"></a><span class="lineno"><a class="line" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a02d06790fb52416a9da6a28b624e9cd9">  107</a></span>&#160;    <span class="keyword">def </span><a class="code" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a02d06790fb52416a9da6a28b624e9cd9">testCatchesSehExceptionsWithCxxExceptionsEnabled</a>(self):</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;      self.<a class="code" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a737bbcc64405854aa8e0aea87ca5850b">TestSehExceptions</a>(EX_BINARY_OUTPUT)</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;</div><div class="line"><a name="l00110"></a><span class="lineno"><a class="line" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a4a181de9de2b147eff55ed7a1d7d40c4">  110</a></span>&#160;    <span class="keyword">def </span><a class="code" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a4a181de9de2b147eff55ed7a1d7d40c4">testCatchesSehExceptionsWithCxxExceptionsDisabled</a>(self):</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;      self.<a class="code" href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a737bbcc64405854aa8e0aea87ca5850b">TestSehExceptions</a>(BINARY_OUTPUT)</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;</div><div class="line"><a name="l00114"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html">  114</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html">CatchCxxExceptionsTest</a>(<a class="code" href="../../d2/d4a/namespacegtest__test__utils.html#acb97a85206c09d233db6c7f2362e5428">gtest_test_utils.TestCase</a>):</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;  <span class="stringliteral">&quot;&quot;&quot;Tests C++ exception-catching behavior.</span></div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;<span class="stringliteral"></span></div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;<span class="stringliteral">     Tests in this test case verify that:</span></div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;<span class="stringliteral">     * C++ exceptions are caught and logged as C++ (not SEH) exceptions</span></div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;<span class="stringliteral">     * Exception thrown affect the remainder of the test work flow in the</span></div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;<span class="stringliteral">       expected manner.</span></div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;<span class="stringliteral">  &quot;&quot;&quot;</span></div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;</div><div class="line"><a name="l00123"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a7d02a890df0e3990aa107288c21f7dc7">  123</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a7d02a890df0e3990aa107288c21f7dc7">testCatchesCxxExceptionsInFixtureConstructor</a>(self):</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;                 <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                 <span class="stringliteral">&#39;in the test fixture\&#39;s constructor&#39;</span></div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInConstructorTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;</div><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;  <span class="keywordflow">if</span> (<span class="stringliteral">&#39;CxxExceptionInDestructorTest.ThrowsExceptionInDestructor&#39;</span> <span class="keywordflow">in</span></div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;      EX_BINARY_OUTPUT):</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;</div><div class="line"><a name="l00136"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a3fe17da71b72c1693fa358f71c6b31be">  136</a></span>&#160;    <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a3fe17da71b72c1693fa358f71c6b31be">testCatchesCxxExceptionsInFixtureDestructor</a>(self):</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;      self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;                   <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;                   <span class="stringliteral">&#39;in the test fixture\&#39;s destructor&#39;</span></div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;      self.assert_(<span class="stringliteral">&#39;CxxExceptionInDestructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;                   <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;                   <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;</div><div class="line"><a name="l00145"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a8e791760b553d92490005deea0812f44">  145</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a8e791760b553d92490005deea0812f44">testCatchesCxxExceptionsInSetUpTestCase</a>(self):</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUpTestCase()&#39;</span></div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInConstructorTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest constructor &#39;</span></div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest destructor &#39;</span></div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::SetUp() &#39;</span></div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::TearDown() &#39;</span></div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest test body &#39;</span></div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;</div><div class="line"><a name="l00168"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a56c906c34e689ee016ab1bf14fe5220c">  168</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a56c906c34e689ee016ab1bf14fe5220c">testCatchesCxxExceptionsInTearDownTestCase</a>(self):</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDownTestCase()&#39;</span></div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;</div><div class="line"><a name="l00173"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a6451307941e063bcc3927992c1f2df54">  173</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a6451307941e063bcc3927992c1f2df54">testCatchesCxxExceptionsInSetUp</a>(self):</div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;                 <span class="stringliteral">&#39; thrown in SetUp()&#39;</span></div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest destructor &#39;</span></div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDown() &#39;</span></div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInSetUpTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;</div><div class="line"><a name="l00191"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a40ba50bf018753b7b21ed93ed60e4e1c">  191</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a40ba50bf018753b7b21ed93ed60e4e1c">testCatchesCxxExceptionsInTearDown</a>(self):</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;                 <span class="stringliteral">&#39; thrown in TearDown()&#39;</span></div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest destructor &#39;</span></div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;</div><div class="line"><a name="l00202"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#ac73b336590a3d1c242124e9ea5464a42">  202</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#ac73b336590a3d1c242124e9ea5464a42">testCatchesCxxExceptionsInTestBody</a>(self):</div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;    self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;                 <span class="stringliteral">&#39; thrown in the test body&#39;</span></div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDownTestCase() &#39;</span></div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest destructor &#39;</span></div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDown() &#39;</span></div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;                 <span class="stringliteral">&#39;called as expected.&#39;</span></div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;</div><div class="line"><a name="l00216"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a922cb0b598034924c19e6695cc9f7513">  216</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a922cb0b598034924c19e6695cc9f7513">testCatchesNonStdCxxExceptions</a>(self):</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unknown C++ exception thrown in the test body&#39;</span></div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;                 <span class="keywordflow">in</span> EX_BINARY_OUTPUT)</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;</div><div class="line"><a name="l00220"></a><span class="lineno"><a class="line" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#af3a794d5af0b3d72789293531468050a">  220</a></span>&#160;  <span class="keyword">def </span><a class="code" href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#af3a794d5af0b3d72789293531468050a">testUnhandledCxxExceptionsAbortTheProgram</a>(self):</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    <span class="comment"># Filters out SEH exception tests on Windows. Unhandled SEH exceptions</span></div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    <span class="comment"># cause tests to show pop-up windows there.</span></div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + <span class="stringliteral">&#39;=-*Seh*&#39;</span></div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    <span class="comment"># By default, Google Test doesn&#39;t catch the exceptions.</span></div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    uncaught_exceptions_ex_binary_output = <a class="code" href="../../d8/dd3/classgtest__test__utils_1_1_subprocess.html">gtest_test_utils.Subprocess</a>(</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;        [EX_EXE_PATH,</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;         NO_CATCH_EXCEPTIONS_FLAG,</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;         FITLER_OUT_SEH_TESTS_FLAG],</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;        env=environ).output</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unhandled C++ exception terminating the program&#39;</span></div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;                 <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;<span class="keywordflow">if</span> __name__ == <span class="stringliteral">&#39;__main__&#39;</span>:</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;  <a class="code" href="../../d2/d4a/namespacegtest__test__utils.html#a5361b42d9c6843b5b117ead4d1c58cc5">gtest_test_utils.Main</a>()</div><div class="ttc" id="namespacegtest__test__utils_html_a5361b42d9c6843b5b117ead4d1c58cc5"><div class="ttname"><a href="../../d2/d4a/namespacegtest__test__utils.html#a5361b42d9c6843b5b117ead4d1c58cc5">gtest_test_utils.Main</a></div><div class="ttdeci">def Main()</div><div class="ttdef"><b>Definition:</b> <a href="../../d3/d8b/gtest__test__utils_8py_source.html#l00306">gtest_test_utils.py:306</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_a7d02a890df0e3990aa107288c21f7dc7"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a7d02a890df0e3990aa107288c21f7dc7">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureConstructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00123">gtest_catch_exceptions_test.py:123</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_a40ba50bf018753b7b21ed93ed60e4e1c"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a40ba50bf018753b7b21ed93ed60e4e1c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDown(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00191">gtest_catch_exceptions_test.py:191</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_a6451307941e063bcc3927992c1f2df54"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a6451307941e063bcc3927992c1f2df54">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUp(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00173">gtest_catch_exceptions_test.py:173</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_a922cb0b598034924c19e6695cc9f7513"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a922cb0b598034924c19e6695cc9f7513">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions</a></div><div class="ttdeci">def testCatchesNonStdCxxExceptions(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00216">gtest_catch_exceptions_test.py:216</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test_html"><div class="ttname"><a href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html">gtest_catch_exceptions_test.CatchSehExceptionsTest</a></div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00085">gtest_catch_exceptions_test.py:85</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_a8e791760b553d92490005deea0812f44"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a8e791760b553d92490005deea0812f44">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInSetUpTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00145">gtest_catch_exceptions_test.py:145</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test_html_a02d06790fb52416a9da6a28b624e9cd9"><div class="ttname"><a href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a02d06790fb52416a9da6a28b624e9cd9">gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled</a></div><div class="ttdeci">def testCatchesSehExceptionsWithCxxExceptionsEnabled(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00107">gtest_catch_exceptions_test.py:107</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test_html_a737bbcc64405854aa8e0aea87ca5850b"><div class="ttname"><a href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a737bbcc64405854aa8e0aea87ca5850b">gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions</a></div><div class="ttdeci">def TestSehExceptions(self, test_output)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00089">gtest_catch_exceptions_test.py:89</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_ac73b336590a3d1c242124e9ea5464a42"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#ac73b336590a3d1c242124e9ea5464a42">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTestBody(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00202">gtest_catch_exceptions_test.py:202</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_af3a794d5af0b3d72789293531468050a"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#af3a794d5af0b3d72789293531468050a">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram</a></div><div class="ttdeci">def testUnhandledCxxExceptionsAbortTheProgram(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00220">gtest_catch_exceptions_test.py:220</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_a3fe17da71b72c1693fa358f71c6b31be"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a3fe17da71b72c1693fa358f71c6b31be">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor</a></div><div class="ttdeci">def testCatchesCxxExceptionsInFixtureDestructor(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00136">gtest_catch_exceptions_test.py:136</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test_html_a4a181de9de2b147eff55ed7a1d7d40c4"><div class="ttname"><a href="../../dc/dec/classgtest__catch__exceptions__test_1_1_catch_seh_exceptions_test.html#a4a181de9de2b147eff55ed7a1d7d40c4">gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled</a></div><div class="ttdeci">def testCatchesSehExceptionsWithCxxExceptionsDisabled(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00110">gtest_catch_exceptions_test.py:110</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html_a56c906c34e689ee016ab1bf14fe5220c"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html#a56c906c34e689ee016ab1bf14fe5220c">gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase</a></div><div class="ttdeci">def testCatchesCxxExceptionsInTearDownTestCase(self)</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00168">gtest_catch_exceptions_test.py:168</a></div></div>
<div class="ttc" id="classgtest__test__utils_1_1_subprocess_html"><div class="ttname"><a href="../../d8/dd3/classgtest__test__utils_1_1_subprocess.html">gtest_test_utils.Subprocess</a></div><div class="ttdef"><b>Definition:</b> <a href="../../d3/d8b/gtest__test__utils_8py_source.html#l00207">gtest_test_utils.py:207</a></div></div>
<div class="ttc" id="namespacegtest__test__utils_html_acb97a85206c09d233db6c7f2362e5428"><div class="ttname"><a href="../../d2/d4a/namespacegtest__test__utils.html#acb97a85206c09d233db6c7f2362e5428">gtest_test_utils.TestCase</a></div><div class="ttdeci">TestCase</div><div class="ttdef"><b>Definition:</b> <a href="../../d3/d8b/gtest__test__utils_8py_source.html#l00077">gtest_test_utils.py:77</a></div></div>
<div class="ttc" id="namespacegtest__test__utils_html_a89ed3717984a80ffbb7a9c92f71b86a2"><div class="ttname"><a href="../../d2/d4a/namespacegtest__test__utils.html#a89ed3717984a80ffbb7a9c92f71b86a2">gtest_test_utils.GetTestExecutablePath</a></div><div class="ttdeci">def GetTestExecutablePath(executable_name, build_dir=None)</div><div class="ttdef"><b>Definition:</b> <a href="../../d3/d8b/gtest__test__utils_8py_source.html#l00156">gtest_test_utils.py:156</a></div></div>
<div class="ttc" id="classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test_html"><div class="ttname"><a href="../../dd/df7/classgtest__catch__exceptions__test_1_1_catch_cxx_exceptions_test.html">gtest_catch_exceptions_test.CatchCxxExceptionsTest</a></div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00114">gtest_catch_exceptions_test.py:114</a></div></div>
<div class="ttc" id="namespacegtest__catch__exceptions__test_html_a60be14c2b88aafb689ba4d3d2578449e"><div class="ttname"><a href="../../dd/dbf/namespacegtest__catch__exceptions__test.html#a60be14c2b88aafb689ba4d3d2578449e">gtest_catch_exceptions_test.SetEnvVar</a></div><div class="ttdeci">SetEnvVar</div><div class="ttdef"><b>Definition:</b> <a href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00061">gtest_catch_exceptions_test.py:61</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_c882bb6fa009938b7b09c7ff2cbfbf0e.html">str</a></li><li class="navelem"><a class="el" href="../../dir_7843869d34b8b4d6e1bd6af8e6d72fdd.html">googletest</a></li><li class="navelem"><a class="el" href="../../dir_a21a0e80132c4b903f36a071ccc3ec77.html">googletest</a></li><li class="navelem"><a class="el" href="../../dir_8e7c983e3fc19a6a3cc10015ebb7269a.html">test</a></li><li class="navelem"><a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py.html">gtest_catch_exceptions_test.py</a></li>
    <li class="footer">構築:
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
